### ISSUE TITLE
Alpine version update?

### ISSUE THREAD

**Issue by wolf99** [exercism/c-test-runner#46]
Hi there,

Is there any specific reason that the Dckerfile uses Alpine pinned at version 3.10 ?
That security support for that version finished 6 months ago.

Follow-up question: is there any specific reason to stick with Alpine at all?
All the track CI uses Ubuntu 18.04 at the moment (update to 20.04 is in the works), so this would be a point of difference between how the website runs submissions and how the track is created.

Tagging @bergjohan as you created it the Dockerfile.
Tagging @ErikSchierboom as I think you probably have the view from the test-runner specification.

**Comment by ErikSchierboom** [comment]
> I think it was suggested that we'd use alpine when we started out with the test runners, to keep the image size small.

Yep. That and the fact that Alpine is a very secure base image makes it our preferred

> I have no idea why I pinned 3.10 though. I probably used an example from somewhere and didn't think about the version. We should probably update that to latest.

Pinning of images in general is a good thing, as it makes the Docker image behave more predictable.

> Since alpine has got everything needed for the test runner, I don't really see a reason to switch to Ubuntu, but feel free to make the switch if you think it's better.

What will be the difference between CI and the test runner? Is there anything that is different from Ubuntu to Alpine?

**Comment by wolf99** [comment]
Hi @ErikSchierboom 

> What will be the difference between CI and the test runner? Is there anything that is different from Ubuntu to Alpine?

I'm not clear if there is a difference TBH. But I was thinking it would narrow down any delta between what the track's CI tests (using Ubuntu on GitHub's workflow runners) and what the  students experience. Hopefully helping to reduce any issues like https://github.com/exercism/c/issues/699

I'm still not really sure what is causing that issue, but reducing the delta might help to narrow down the possibilities.

**Comment by ErikSchierboom** [comment]
Do you have any indication of the size difference between an Ubuntu-based vs Alpine-based image?
