### ISSUE TITLE
Tests pass locally but not online

### ISSUE THREAD

**Issue by yorange1** [exercism/c-test-runner#56]
![image](https://user-images.githubusercontent.com/28107329/150183613-af892f1b-e3cc-4b8b-ace4-daabc973e17e.png)

The log output shows that I passed all the tests, but the page shows that there was an error.

**Comment by bobahop** [comment]
Also for this solution

```c
#include "isogram.h"
#include <ctype.h>
#include <string.h>

bool is_isogram(const char phrase[]){
    if (phrase == NULL) {
        return false;
    }

    size_t len = strlen(phrase);
    bool in[26];
    for (size_t i = 0; i < 26; i++){
        in[i] = false;
    }
    
    for (size_t i=0; i<len; i++){
        char c = phrase[i];
        if (c >= 'A' && c <= 'Z'){
            c = tolower(c);
        }

        if (c >= 'a' && c <= 'z'){
            if (in[c - 'a'] == true){
                return false;
            }
            in[c - 'a'] = true;
        }
    }

    return true;
}





#ifndef ISOGRAM_H
#define ISOGRAM_H

#include <stdbool.h>

bool is_isogram(const char phrase[]);

#endif
```

**Comment by siebenschlaefer** [comment]
This is related to https://github.com/exercism/c/pull/744
Either the test runner has to be fixed or `-DUNITY_OUTPUT_COLOR` removed from the makefiles

**Comment by wolf99** [comment]
https://github.com/exercism/c-test-runner/pull/57 was just merged, which should resolve this 🤞

If you can confirm if the issue is no longer seen, then this issue can be closed.

**Comment by bobahop** [comment]
Still happening. Maybe takes a while to propagate?

**Comment by bobahop** [comment]
Okay, looks good now!

**Comment by yorange1** [comment]
> #57 was just merged, which should resolve this 🤞
> 
> If you can confirm if the issue is no longer seen, then this issue can be closed.

Great, it`s work now. 

And the output of local and online editors looks better. 👍

**Comment by ezgbreezy** [comment]
2/21/23: I appear to currently be having this same issue with the isogram exercise, tests pass locally, fail online after CLI submission. Double checked, it is not a `TEST_IGNORE` issue.

<img width="488" alt="Screenshot 2023-02-21 at 9 11 03 PM" src="https://user-images.githubusercontent.com/62525634/220503140-eeb4e069-d9b5-4128-b256-431f213d16e8.png">

<img width="662" alt="Screenshot 2023-02-21 at 9 11 13 PM" src="https://user-images.githubusercontent.com/62525634/220503180-c6ac439f-c266-4cf3-9cf3-f410c43aa154.png">

## Submitted files:

### isogram.c
```c
#include "isogram.h"

bool is_isogram(const char phrase[])
{
    // Check if NULL
    if (phrase == NULL)
    {
        return false;
    }

    // Create working copy of phrase
    char *input = malloc(strlen(phrase) + 1);
    strcpy(input, phrase);
    
    // Create counter, set to zero
    int counter[26];
    for (int i = 0; i < 26; i++)
    {
        counter[i] = 0;
    }

    // Convert to lowercase
    for (int i = 0; phrase[i] != '\0'; i++)
    {
        input[i] = tolower(phrase[i]);
        if (input[i] != ' ' && input[i] != '-')
        {
            counter[input[i] - 97]++;
        }
        if (counter[input[i] - 97] > 1)
        {
            return false;
        }
    }

    // Free copy
    free(input);

    return true;
}
```

### isogram.h

```c
#ifndef ISOGRAM_H
#define ISOGRAM_H

#include <ctype.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>

bool is_isogram(const char phrase[]);

#endif
```

**Comment by ryanplusplus** [comment]
@ezgbreezy try running `make memcheck`. I'm pretty sure that you are writing out of bounds in `counter` because you're not confirming that `input[i]` is alphabetic (ie: A-Z, a-z). This can pass locally if you're lucky with the contents of the `malloc`ed memory.

Unrelated to your issue, I'd look for a way to solve this problem without using `malloc`. `input` does not look like it's necessary to your solution.

**Comment by siebenschlaefer** [comment]
@ezgbreezy There are a few issues in that solution:

- The `.c` file calls `malloc()`, `free()`, `strlen()`, `strcpy()`, and `tolower()` but does not include `<ctype.h>`, `<stdlib.h>`, nor `<string.h>`.
- `phrase` is `const`, but the second loop attempts to modify it (`input[i] = tolower(phrase[i]);`)
- The first `if` in the second loop skips spaces an hyphens, but the second `if` accesses `counter[input[i] - 97]` unconditionally which is out of bounds if the current character is a space or hyphen.
- At the end of the function `free(input);` deallocates the `input`, but if the second loop finds a duplicate the function returns without deallocating.
- The first line of the second loop passes a `char` to `tolower()`. This `tolower()` comes with a catch: It takes an `int` and its behavior is undefined if its argument is neither representable by an `unsigned char` nor equal to `EOF`. You should never pass a `char` or a `signed char` to `tolower()` but always cast it to `unsigned char` first (see also [cppreference](https://en.cppreference.com/w/c/string/byte/tolower)).

@ryanplusplus is correct, `make memcheck` should be able to produce errors or warnings for all of those issues, except for the last one.

**Comment by ezgbreezy** [comment]
@ryanplusplus
> @ezgbreezy try running `make memcheck`. I'm pretty sure that you are writing out of bounds in `counter` because you're not confirming that `input[i]` is alphabetic (ie: A-Z, a-z). This can pass locally if you're lucky with the contents of the `malloc`ed memory.

`memcheck` passes all tests:

<img width="681" alt="Screenshot 2023-02-22 at 11 29 57 AM" src="https://user-images.githubusercontent.com/62525634/220697367-69973554-3a0e-4736-8e98-336027ea8a62.png">

**Could you elaborate on why you think not manually checking if `input[i]` is alphabetic would lead to writing out of bounds?**

Correct me if I'm wrong, but here a `char *` of the same size as `phrase` is allocated and then `phrase` is copied to `input`.  
Why would the values within `phrase`  or `input` make a difference in accessing memory outside of `input`? Am I missing something here?

> Unrelated to your issue, I'd look for a way to solve this problem without using `malloc`. `input` does not look like it's necessary to your solution.

I agree that input (making a copy in general) may not be necessary for all solutions but since `phrase` is a `const char` it is read-only and I can't modify it. It would have been a lot more involved to check lowercase letters against uppercase letters, so converting made more sense to me, hence the copy.

**Comment by ezgbreezy** [comment]
@siebenschlaefer Thanks for this breakdown!
> @ezgbreezy There are a few issues in that solution:
> 
> * The `.c` file calls `malloc()`, `free()`, `strlen()`, `strcpy()`, and `tolower()` but does not include `<ctype.h>`, `<stdlib.h>`, nor `<string.h>`.

All of the libraries are included in the `isogram.h` header file, is there a reason they should be in the .c file instead?


> * `phrase` is `const`, but the second loop attempts to modify it (`input[i] = tolower(phrase[i]);`)

Hm, but doesn't `tolower` not modify the value of its inputs? And if that were true wouldn't the program not have compiled and instead given me a read-only error?


> * The first `if` in the second loop skips spaces an hyphens, but the second `if` accesses `counter[input[i] - 97]` unconditionally which is out of bounds if the current character is a space or hyphen.
> * At the end of the function `free(input);` deallocates the `input`, but if the second loop finds a duplicate the function returns without deallocating.

Good catch! Interesting that `memcheck` didn't catch the free error. Maybe I'll try another instance running valgrind instead. 

**Accessing memory out of bounds of `counter` was the issue!** I implemented the following and it worked:

```c

for (int i = 0; phrase[i] != '\0'; i++)
    {
        input[i] = tolower(phrase[i]);

        if (input[i] != ' ' && input[i] != '-')
        {
            counter[input[i] - 'a']++;

            if (counter[input[i] - 'a'] > 1)
            {
                free(input);
                return false;
            }
        }
        
    }
```


> * The first line of the second loop passes a `char` to `tolower()`. This `tolower()` comes with a catch: It takes an `int` and its behavior is undefined if its argument is neither representable by an `unsigned char` nor equal to `EOF`. You should never pass a `char` or a `signed char` to `tolower()` but always cast it to `unsigned char` first (see also [cppreference](https://en.cppreference.com/w/c/string/byte/tolower)).

Interesting, so in this instance, assuming you were going to use `tolower`, would you have instead cast `phase[i]` to an `unsigned char` or used a conditional to only pass unsigned ints? Isn't casting constant variables considered bad practice? 

```c
input[i] = tolower((unsigned char) phrase[i]);

// or something more like:

if (phrase[i] > 0)
{
    input[i] = tolower(phrase[i]);
}
else
{
    input[i] = phrase[i];
}
```

**Comment by ryanplusplus** [comment]
> **Could you elaborate on why you think not manually checking if `input[i]` is alphabetic would lead to writing out of bounds?**

The out of bounds write was to `counter` since you were indexing into something with length 26 without checking that it's actually a letter.

> I agree that input (making a copy in general) may not be necessary for all solutions but since phrase is a const char it is read-only and I can't modify it. It would have been a lot more involved to check lowercase letters against uppercase letters, so converting made more sense to me, hence the copy.

You only use one character of `input` at a time, so you can replace a `malloc`ed buffer of the same length as `phrase` with a single `char` variable.

```c
    for (int i = 0; phrase[i] != '\0'; i++)
    {
        char c = tolower(phrase[i]);

        if (c != ' ' && c != '-')
        {
            counter[c - 'a']++;

            if (counter[c - 'a'] > 1)
            {
                return false;
            }
        }
        
    }
```

**Comment by ezgbreezy** [comment]
I understand what you're saying now, thanks for elaborating. 

Something like this would be better then:

```c
    for (int i = 0; phrase[i] != '\0'; i++)
    {
        char c = tolower(phrase[i]);

        if (isalpha(c))
        {
            counter[c - 'a']++;

            if (counter[c - 'a'] > 1)
            {
                return false;
            }
        }
        
    }
```

**Comment by ryanplusplus** [comment]
> I understand what you're saying now, thanks for elaborating.
> 
> Something like this would be better then:
> 
> ```c
>     for (int i = 0; phrase[i] != '\0'; i++)
>     {
>         char c = tolower(phrase[i]);
> 
>         if (isalpha(c))
>         {
>             counter[c - 'a']++;
> 
>             if (counter[c - 'a'] > 1)
>             {
>                 return false;
>             }
>         }
>         
>     }
> ```

Yes :+1:
